/**
 * Curated clip-creation ideas per canonical character slug.
 * Written for Kling image-to-video: one environment, 1–2 readable motions per beat,
 * natural pacing (6–10s total), visible dilemma at the end — no resolution.
 */

export type CharacterClipSuggestions = {
  locations: string[];
  actions: string[];
  cliffhangers: string[];
};

const EMPTY: CharacterClipSuggestions = {
  locations: [],
  actions: [],
  cliffhangers: [],
};

export const CLIP_SUGGESTIONS_BY_SLUG: Record<string, CharacterClipSuggestions> = {
  nina: {
    locations: [
      "Quiet corner office at dusk, city lights through glass",
      "Hotel lobby with low marble and a single reception desk",
      "Conference room before anyone else arrives, projector idle",
      "Upscale café window seat, rain faint on glass",
      "Airport gate lounge, rows of empty seats, one screen flashing",
      "Rooftop terrace with planters, wind moving papers on a low table",
      "Law library reading table, tall shelves and green lamps",
      "Boutique hotel corridor, soft carpet, numbered doors",
      "Co-working quiet pod, frosted glass, one free chair",
      "Private art gallery room, three pieces on white walls",
    ],
    actions: [
      "A colleague slides a printed deck across the table; Nina has not opened it yet and holds her pen still over her notes.",
      "Two people disagree in hushed tones; Nina stands between them with a tablet, listening without turning toward either yet.",
      "Someone says her name in an adjacent conversation; she pauses mid-sip of coffee, eyes lifting slowly toward the sound.",
      "A client appears early through the glass door; Nina rises from her chair with a folder in one hand, one step toward the door.",
      "An urgent email lights her phone; she sets the phone face-down on the table and exhales, fingers flat on the wood.",
      "The elevator opens on the wrong floor; she reads the directory plaque, hesitating before stepping back inside.",
      "A mentor's voice memo plays; Nina holds the phone to her ear, expression neutral, thumb hovering over reply.",
      "During a presentation the clicker fails; she glances toward the technician in the doorway while the audience waits.",
      "Someone places a sealed envelope on her desk; she does not touch it, studying the handwriting on the front.",
      "Rain streaks the window behind a merger chart; Nina traces one printed line with her finger, the motion unfinished.",
    ],
    cliffhangers: [
      "Hand frozen halfway to the door handle; she has heard her name spoken again behind her.",
      "Two contract versions lie side by side; her pen tip hovers, not committing to either signature line.",
      "The phone shows two missed calls from the same client, different numbers; she has not answered either.",
      "Elevator doors begin to close; a foot appears in the gap but she cannot see who it belongs to yet.",
      "She turns toward the glass wall and sees her reflection overlapping a figure in the room beyond.",
      "Thumb resting on send for an email she rewrote three times; she lifts her finger without pressing.",
      "Someone asks which pen to use; blue and black are offered side by side; she stares without reaching.",
      "The slide advances to a blank screen; she faces the room in silence, remote loose in her hand.",
      "Her name appears on a screen share she did not queue; the cursor is not hers.",
      "A second chair at the small table is pulled out; no one has sat down yet.",
    ],
  },

  lila: {
    locations: [
      "Denim wall at a bright clothing store, folded stacks and size tags",
      "Sneaker aisle with mirrors along the floor",
      "Thrift store jacket rack, plastic hangers crowded",
      "Mall food court table with shopping bags piled",
      "Dressing room area, curtain half open on an empty stall",
      "Accessory wall with rows of sunglasses and caps",
      "Checkout line with impulse-buy bins on both sides",
      "Phone accessory kiosk, cables and cases under glass",
      "Vintage band tee section, crates and cardboard signs",
      "Pastel hoodie display, soft lighting and sale signs",
    ],
    actions: [
      "Two denim cuts hang on the same hook; Lila holds the waistbands against her hips, switching them back and forth slowly.",
      "Three sneaker boxes sit at her feet in the mirror; she lifts one lid, then another, unable to settle.",
      "Her phone shows a text: \"get the green one\"; she stares at green and blue folded side by side on the shelf.",
      "A sale sign flips from thirty to forty percent as she reaches; she pulls her hand back toward her pocket.",
      "She tries a cap forward and backward in the mirror, chin tilted, neither look fully chosen.",
      "The checkout beep starts; she realizes she still holds a second top tucked under the first on the counter.",
      "Rainbow socks catch her eye mid-walk; she stops with one foot already past the end of the display.",
      "A mannequin wears the jacket she wanted yesterday; today only a different color hangs on the rack.",
      "Her phone shows low battery; she needs to choose between paying now or browsing one more rack.",
      "Two friends wave from different store entrances; she pivots halfway between them, bags swinging once.",
    ],
    cliffhangers: [
      "Both dressing-room curtains are occupied; she clutches two sizes and has not knocked on either.",
      "One sneaker is on her foot, the other still in the box; laces untied, she has not stood up yet.",
      "Her thumb hovers between two payment apps; the totals do not match on the screens.",
      "The mirror shows someone behind her holding the last hoodie in her size.",
      "She has stepped onto the cold floor in socks; both pairs of shoes still sit on the bench.",
      "The tag says final sale; the hanger is still in her hand, the item unworn on the hook.",
      "The elevator opens to the wrong parking color zone; bags drag on her arm.",
      "A friend says five minutes while the store announces closing in four over the speaker.",
      "Checkout beeps twice for the same item; she has not said which register she is using.",
      "One tag says M and the sibling hanger says S; both pieces are in her hands.",
    ],
  },

  earl: {
    locations: [
      "Hardware store paint aisle, fan decks and metal shelves",
      "Ranch porch with rocking chairs and heat shimmer",
      "Small-town diner booth, laminate table and window glare",
      "Gas station pump island, concrete and distant highway",
      "Bait shop counter, Styrofoam coolers stacked",
      "Feed store loading area, pallets and shade",
      "Barber shop waiting bench, trophy fish on the wall",
      "Courthouse steps in harsh midday sun",
      "Tractor supply shade structure, bulk bags",
      "BBQ joint picnic table, sauce bottles and napkins",
    ],
    actions: [
      "A clerk offers a tablet instead of a paper form; Earl squints at both without taking either.",
      "A neighbor revs a loud car; Earl lowers his newspaper one inch, cigar steady between fingers.",
      "A grandkid asks him to choose streaming or cable; the remote sits between them on the armrest.",
      "A new digital thermometer beeps; Earl taps the old analog one in his shirt pocket without pulling it out.",
      "Two hunters debate cartridge brands across the counter; Earl listens, thumb hooked on his belt loop.",
      "Rain starts; he holds truck keys in one hand and a porch coffee in the other, neither lifted yet.",
      "A stray dog approaches his boots; he does not move the cigar, eyes on the collar without a tag.",
      "The clerk says the cash-only line is shorter; his wallet stays closed in his palm.",
      "Wind flips the newspaper to sports; the obituaries were on the other side — he has not turned back.",
      "Someone offers sugar-free pie; his fork hovers over his own slice, untouched.",
    ],
    cliffhangers: [
      "Two rocking chairs; one creaks when the wind shifts; he has not sat down yet.",
      "Cigar ash holds a long inch; the doorbell rings and he does not tap it off.",
      "A lottery ticket in his hand; the register asks quick-pick yes or no; his mouth stays closed.",
      "A grandkid's drone buzzes overhead; his hat stays on, his gaze fixed straight ahead.",
      "Both pumps show different prices per gallon; the truck cap is open, nozzle not lifted.",
      "The barber asks same as usual but the wall photo looks decades old; the mirror waits.",
      "Thermostat screen asks heat or cool; his thumb has not pressed either.",
      "Thunder cracks; the porch swing chain shifts; he has not shifted his weight.",
      "Two pie tins on the counter — one his recipe, one store-bought label facing him.",
      "Granddaughter offers her phone for photos; his flip phone is already open on contacts.",
    ],
  },

  viktor: {
    locations: [
      "Curbside beside a vintage car, hood cool in shade",
      "Corner store with a security mirror above the register",
      "Stairwell landing, graffiti and a single bare bulb",
      "Late-night food truck queue, steam and string lights",
      "Pawn shop glass counter, items layered behind",
      "Underground parking column, tire marks and echo",
      "Boxing gym corner, heavy bag and chain slack",
      "Rooftop near a water tank, city haze at the edge",
      "Bar doorway with neon spill on wet sidewalk",
      "Outdoor basketball court, chain-link and one hoop lit",
    ],
    actions: [
      "Two drivers argue over a parking spot; Viktor stands beside his car, keys rotating slowly on one finger.",
      "Someone slides folded cash through the food truck window ahead of the order; he watches the cook's reaction.",
      "His phone vibrates with two names; he does not look down yet, shoulders loosening once.",
      "Rain makes a taped poster run; he reads an address wrong once, blinks, reads again slowly.",
      "Change hits the counter; his palm stays flat, not lifting the coins.",
      "A dog chain rattles behind a fence; he stops mid-step, one foot half off the curb.",
      "Neon reflects red then blue on wet pavement; he does not turn his head, breathing slower.",
      "A friend offers a ride north or south; the passenger door is open, engine idling.",
      "A scraped knuckle bleeds slow; paper towels offered from left and right — neither taken yet.",
      "The old car door sticks; he pulls once, twice, listening for something deeper in the alley.",
    ],
    cliffhangers: [
      "Two stairwells branch; one bulb is dead; his boots point between them without a step.",
      "The food truck menu flips to sold out on his item while he is next in line.",
      "The car hood is warm; a second keyring is visible on the driver's seat through the glass.",
      "His phone shows a live location moving toward him; he has not unlocked the screen.",
      "Offered a handshake or a fist bump; both of his arms lift slightly and freeze.",
      "A backpack on the ground is not his colors; his boot toe stops one inch short.",
      "A friend repeats a question; the car door behind him stays ajar.",
      "A QR code on a flyer is soggy; the walk sign flickers but his foot has not left the curb.",
      "Keys jingle at the wrong pitch; his pocket pat slows, not finished.",
      "A voice from the alley does not match the face he expected; his shoulder is turned halfway.",
    ],
  },

  baxter: {
    locations: [
      "Armory check-in desk, clipboard and key hooks",
      "Training field bleachers, empty metal rows",
      "Base commissary queue, cordons and signs",
      "Briefing room with a map wall and chairs in rows",
      "Barracks aisle, footlockers and thin mattresses",
      "Motor pool vehicle line, hoods and chalk marks",
      "Obstacle course start line, chalk digits on gravel",
      "Memorial stone path, flags at half-mast",
      "Supply closet shelf, labeled bins and dust",
      "Chapel foyer before service, pamphlets and hush",
    ],
    actions: [
      "Two NCOs mention slightly different formation times; Baxter's boot crease does not shift, eyes on the middle distance.",
      "A new private salutes with the wrong hand; the correction hangs in the air — Baxter has not spoken yet.",
      "A clipboard offers a red pen or a black pen; both are clipped; weather has not let him choose.",
      "A rain patch moves across the field; the schedule says hold; a watch second hand is visible on his wrist.",
      "His phone buzzes with a family photo ID; formation is ten seconds out, pocket seam pressed flat.",
      "Two chow hall lines look equal length; his tray stays empty in both hands.",
      "A glove fits the left hand, not the right; a spare pair waits in a locker twenty meters back, door latched.",
      "A helmet strap dangles; wind lifts the brim once; he adjusts by a thumb width, not the buckle.",
      "A map pin lands between grid squares; his fingertip traces the fold, not the dot.",
      "A private drops a canteen; it rolls between two boots; Baxter has not shifted to retrieve it.",
    ],
    cliffhangers: [
      "\"At ease\" is given but the commander still faces him; his shoulders hover millimeters from relaxing.",
      "Two whispered orders come from behind; rank is visible on only one shadow.",
      "One foot is on the first low wall; the whistle is half-raised — not for his lane or not yet.",
      "Ruck straps hang with equal slack; the left buckle was adjusted once, the right untouched.",
      "The fire-watch board shows two names in one slot; a dry-erase cap sits in his teeth, not the marker.",
      "Canteen spout aligns with his lip; water is not tipped; a silent count continues in his ear.",
      "A boot print in mud overlays an older one; he has not matched toe direction yet.",
      "A flag rope is frayed; a clip rests in his palm while his eye stays on the knot, not the pole.",
      "A night-vision case is latched; one battery bar glows red; the overhead bulb is still on.",
      "A shadow crosses the PT field; a whistle ring sits on his thumb, not lifted.",
    ],
  },

  malik: {
    locations: [
      "Home kitchen island, bowls and a warm stove",
      "Brunch line kitchen, pass window and tickets",
      "Farmers market stall, herbs in sun and shade",
      "Bakery display case in early morning light",
      "Food truck prep counter, squeeze bottles in a row",
      "Spice shop wall of glass jars and labels",
      "Apartment stove with two burners hissing",
      "Potluck folding table, foil pans and tongs",
      "Glassware cabinet with one bulb lit inside",
      "Sink full of suds, knives visible along the rim",
    ],
    actions: [
      "Two timers beep one second apart; salt in one hand, pepper grinder in the other, stove hiss between them.",
      "Batter looks wrong; the whisk slows mid-bowl while a recipe card lies face-down beside it.",
      "A customer asks for a vegan swap; the pan already holds butter foam; the flame is not lowered yet.",
      "The last egg cracks uncertain; his thumb feels shell fragment; compost and trash are each one step away.",
      "He lines up a plate for a photo; a fork sits off by an inch — he lifts only the plate edge.",
      "The gas clicks without flame; an electric switch glows nearby; his hand hovers at the drawer knob.",
      "A sous chef slides diced onion to the left board then the right; his knife tip still touches the wood.",
      "Steam fogs his glasses; a towel hangs on shoulder and apron string; neither is lifted to the lens yet.",
      "Pancake batter pours in a thin stream; the first circle spreads uneven; the spatula has not left the hook.",
      "A tasting spoon offers two sauces; his lips have not touched either rim.",
    ],
    cliffhangers: [
      "A pancake hangs mid-flip; the spatula angle holds; the landing side is not visible yet.",
      "Two bottles share a label but different years; the corkscrew touches one neck then the other.",
      "Smoke threads thin then thick; the lid is lifted a crack; his eye is not committed to opening it fully.",
      "Steam clears a heart shape on the pot lid; the spoon has not stirred; the handle points between burners.",
      "A customer taps the counter in rhythm; the third pancake is not committed to the flip.",
      "An ice bath waits for shrimp; his hand hovers the bowl rim while a towel slips on the opposite shoulder.",
      "A blender lid hisses once; his pulse finger stays straight, not curved on the button.",
      "Tweezers hover parsley versus chive; the plate already sits under the pass light.",
      "Dish spray hits his sleeve; the printer starts a second ticket line while he is still reading the first.",
      "An oven mitt is on his left hand only; his right grips the door handle; heat washes the knuckles, not pulled back.",
    ],
  },

  darius: {
    locations: [
      "Barbershop mirror row, chairs and cape folds",
      "Wholesale warehouse aisle, high shelves and pallets",
      "Used car lot front line, windshield stickers",
      "Sneaker consignment back room, boxes stacked",
      "Farmers market bulk bins, scoop hooks",
      "Gas station snack matrix behind glass",
      "Outdoor grill store clearance racks",
      "Pawn shop display case, tags and glare",
      "Department store returns desk, tape and scanner",
      "Barbershop cash counter, tip jar and cards sign",
    ],
    actions: [
      "Two hoodies look identical but the price tags differ; his thumb traces a seam while his eyes stay on the label.",
      "The seller says cash only today; his wallet is half out, card edges visible, bill fold thick.",
      "A text shows the same shoes cheaper online; the fitting-room mirror shows only his socks on the floor.",
      "A bulk scoop overflows the scale; the clerk waits with a second bag; his hand is on neither tie yet.",
      "The barber chair spins to the mirror; two fade photos on the wall — this week's cuts are hard to match.",
      "A lot attendant points to row A then row B; keys warm his palm while two windshield prices differ.",
      "The last rib sits on the tray; tongs hover family-style; his plate edge stops short of the dish center.",
      "A return policy sign flips between thirty and fourteen days; receipt corner in his fist, date unread.",
      "One sneaker box lid is half open; tissue in one shoe is smooth, in the other crumpled; insoles compared without a full lift.",
      "Propane exchange cage shows a blue cap tank and a rusty valve; the wheel has not turned yet.",
    ],
    cliffhangers: [
      "A spoken deal price hangs in the air; palms are millimeters apart; watch glass catches the light.",
      "Two fives and a ten for change; the register suggests a round-up donation; coins are not counted.",
      "Key fob lights flash the wrong adjacent car; door chrome is cool; his grip has not closed.",
      "The next chair's client names the same cut in another language; both chairs swivel inward.",
      "A bulk price sign peels; the decimal is hidden under tape lifting at one corner.",
      "A loyalty scanner beeps invalid; the phone app shows duplicate accounts; thumb hovers delete, not confirm.",
      "Rain starts over the convertible row; a cover is half-pulled; the salesman holds an umbrella offset left.",
      "A clipboard asks cash or finance; pen cap sits in his mouth; the first stroke of his initial is not down.",
      "Neon OPEN flickers to a broken letter; the hallway shows two depths of shadow; one foot rests on the threshold mat only.",
      "The receipt printer runs out mid-total; zeros show but the last digit is a missing line.",
    ],
  },

  yuki: {
    locations: [
      "Quiet manga aisle in a bookstore, tall shelves",
      "Cat café window booth, cushions and low tables",
      "Pastel bakery display case, steam inside glass",
      "Art supply marker wall, caps color-ordered",
      "Small stationery shop sticker shelves",
      "Dorm courtyard bench at dusk, one path lamp",
      "Convenience store dessert cooler, fogged door",
      "Craft fair handmade table, cloth and jars",
      "Quiet laundromat folding corner, warm machines",
      "Botanical greenhouse mist, ferns and gravel path",
    ],
    actions: [
      "Two washi tapes share the same width but different patterns; she lifts one, sets it down, and does not peel the price sticker.",
      "A cat stretches on a cushion; a treat jar lid clicks at the counter; her hand rests on her bag strap, not her pocket.",
      "Headphones slide from her neck; staff asks for her order; twelve drinks on the board, her eyes stuck on the third row.",
      "A sticker sheet corner lifts in the humidity; she presses it flat with one finger, other designs untouched.",
      "Someone holds the door from behind; she steps aside mid-step, both feet in the threshold shadow.",
      "A sketchbook page stays blank; the reference photo on her phone dims to lock before a line is drawn.",
      "A Ferris line splits single riders from groups; she counts painted footprints twice, shoes on the wrong mark.",
      "Gel pen test scribbles on a pad; blue and lavender caps are both off; the point hovers over white space.",
      "Bakery tongs touch a melon bun then a cream puff; steam fogs the glass between her breath and the pastry.",
      "Three dryers buzz; hers is the middle number; a detergent pod squishes in her palm, not tossed yet.",
    ],
    cliffhangers: [
      "A cat head-butts her shin; a second cat blinks from the next stool; her lap is still empty.",
      "A locker coin returns twice to the same slot; mascot keychains swing; the key is not inserted.",
      "The shopkeeper says last one; a box behind the counter and a duplicate on display both show in the mirror.",
      "Rain starts; a clear umbrella crosses shafts with a printed character face; ends tangle on tile, not separated.",
      "Photo mode locks a face-detect box on a stranger; the shutter is half-pressed, blur only in the preview.",
      "Escalator up versus quiet stairs; the handrail is warm; her toe edge does not leave the tactile dots.",
      "Crosswalk chirp speeds at one corner; boots stay planted while the light begins the next phase.",
      "Two drink lids have different straw holes; boba stacks uneven through plastic; straw paper torn halfway.",
      "Wind flips a manga page she was saving; a bookmark ribbon slips at her knuckle; she has not reread the number.",
      "Hoodie drawstring beads sit uneven; one locks at her neck; the mirror cuts at nose level only.",
    ],
  },
};

export function getClipSuggestionsForSlug(
  slug: string | null | undefined,
): CharacterClipSuggestions {
  if (!slug) return EMPTY;
  return CLIP_SUGGESTIONS_BY_SLUG[slug] ?? EMPTY;
}
